name: Simple Login UI
description: "Login UI with Flutter, no backend"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mari-potter-Zh0mcQuw_EQ-unsplash.jpg
    - assets/fonts/GreatVibes-Regular.ttf  # Font added to assets
  fonts:
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf  # Correct font path
